// Claude Code injects synthetic `user` turns into its own transcript when a
// LOCAL slash command runs (`/context`, `/compact`, …). They are addressed to
// the CLI, not to us, and they carry no operator text:
//
//   <local-command-caveat>Caveat: The messages below were generated by the
//   user while running local commands. DO NOT respond to these messages…
//   </local-command-caveat>
//
//   <command-name>/context</command-name>
//     <command-message>context</command-message>
//     <command-args></command-args>
//
// Kato replayed them verbatim as "YOU ASKED" bubbles, so running one local
// command dropped two spurious operator turns into the middle of the chat —
// which is what the operator saw as "he sends these messages automatically".
//
// The rule here is deliberately narrow: a turn is hidden only when NOTHING
// but this scaffolding is in it. A real message that happens to sit next to a
// command envelope still renders, in full — dropping an operator's actual
// words would be far worse than showing one stray envelope.

// Wrappers whose inner text is scaffolding too (the command's own name and
// arguments). Removed whole when testing whether a turn is empty.
const SCAFFOLD_ELEMENTS = [
  'local-command-caveat',
  'command-name',
  'command-message',
  'command-args',
];

// Wrappers around REAL command output. Only the tags are scaffolding — the
// text between them is content, so a turn carrying it is never hidden.
const OUTPUT_ELEMENTS = [
  'local-command-stdout',
  'local-command-stderr',
];

function elementPattern(names, keepInner) {
  const group = names.join('|');
  return keepInner
    ? new RegExp(`</?(?:${group})>`, 'gi')
    : new RegExp(`<(?:${group})>[\\s\\S]*?</(?:${group})>|<(?:${group})\\s*/>`, 'gi');
}

const SCAFFOLD_RE = elementPattern(SCAFFOLD_ELEMENTS, false);
// Unclosed/truncated scaffolding still shouldn't read as an operator turn.
const ORPHAN_TAG_RE = elementPattern([...SCAFFOLD_ELEMENTS, ...OUTPUT_ELEMENTS], true);

// What remains of a user turn once every CLI-internal wrapper is discarded.
// Exported for the tests; callers want `isLocalCommandScaffolding`.
export function stripLocalCommandEnvelope(text) {
  return String(text == null ? '' : text)
    .replace(SCAFFOLD_RE, ' ')
    .replace(ORPHAN_TAG_RE, ' ')
    .trim();
}

// True when a user turn is ENTIRELY Claude Code's local-command scaffolding
// and therefore has nothing to show the operator. Empty text is not
// scaffolding — an empty turn is already handled by the callers' own
// "no prompt text" path, and conflating the two would hide image-only turns.
export function isLocalCommandScaffolding(text) {
  const raw = String(text == null ? '' : text);
  if (!raw.trim()) { return false; }
  return stripLocalCommandEnvelope(raw) === '';
}
