# @package core_lib
youtrack_core_lib:
    base_url: ${oc.env:YOUTRACK_BASE_URL,"https://your-company.youtrack.cloud"}
    token: ${oc.env:YOUTRACK_TOKEN,""}
    project: ${oc.env:YOUTRACK_PROJECT,""}
    assignee: ${oc.env:YOUTRACK_ASSIGNEE,"me"}
    progress_state_field: ${oc.env:YOUTRACK_PROGRESS_STATE_FIELD,"State"}
    progress_state: ${oc.env:YOUTRACK_PROGRESS_STATE,"In Progress"}
    review_state_field: ${oc.env:YOUTRACK_REVIEW_STATE_FIELD,"State"}
    review_state: ${oc.env:YOUTRACK_REVIEW_STATE,"To Verify"}
    issue_states: ${oc.env:YOUTRACK_ISSUE_STATES,"Todo,Open"}
    max_retries: ${oc.decode:${oc.env:YOUTRACK_CORE_LIB_MAX_RETRIES,"3"}}
