# @package bitbucket_core_lib
core-lib:
    bitbucket-core-lib:
        base_url: ${oc.env:BITBUCKET_ISSUES_BASE_URL,"https://api.bitbucket.org/2.0"}
        token: ${oc.env:BITBUCKET_API_TOKEN,""}
        username: ${oc.env:BITBUCKET_USERNAME,""}
        api_email: ${oc.env:BITBUCKET_API_EMAIL,""}
        workspace: ${oc.env:BITBUCKET_ISSUES_WORKSPACE,""}
        repo_slug: ${oc.env:BITBUCKET_ISSUES_REPO_SLUG,""}
        max_retries: ${oc.decode:${oc.env:BITBUCKET_CORE_LIB_MAX_RETRIES,"3"}}
